"""
Content Generator Module - Stories, articles, code, and more
"""

import random
import time
from datetime import datetime
from typing import List, Dict, Optional
import re

class ContentGenerator:
    """Generate various types of content"""
    
    def __init__(self):
        self.templates = self._load_templates()
        
    def _load_templates(self) -> Dict:
        """Load content templates"""
        return {
            'story_openings': [
                "In a world where {element} ruled supreme,",
                "It was a dark and stormy night when {character} discovered that",
                "The year is 2147, and humanity has finally achieved {achievement},",
                "Legend speaks of a time when {mythical_being} walked among us,",
                "In the small town of {town}, something extraordinary was about to happen:"
            ],
            'story_elements': {
                'element': ['magic', 'technology', 'nature', 'love', 'fear', 'hope'],
                'character': ['the chosen one', 'a young inventor', 'an ancient wizard', 'a lost traveler'],
                'achievement': ['space travel', 'immortality', 'world peace', 'time manipulation'],
                'mythical_being': ['dragons', 'phoenixes', 'unicorns', 'elementals'],
                'town': ['Oakhaven', 'Mistvale', 'Stormridge', 'Silverwood']
            }
        }
    
    def generate_story(self, prompt: str, lines: int = 30) -> str:
        """Generate a story with minimum line count"""
        # Extract theme
        theme = self._extract_theme(prompt)
        
        # Generate story
        story = self._create_story(theme)
        
        # Ensure minimum lines
        story_lines = story.split('\n')
        if len(story_lines) < lines:
            additional_lines = lines - len(story_lines)
            story += self._generate_continuation(theme, additional_lines)
        
        return f"📖 **Story: {theme.title()}**\n\n{story}\n\n✨ *Story generated by Skatlaz AI*"
    
    def _extract_theme(self, prompt: str) -> str:
        """Extract story theme from prompt"""
        # Remove common words
        theme = re.sub(r'(story|about|tell|write|create|generate|a|an|the)', '', prompt, flags=re.IGNORECASE)
        theme = theme.strip()[:50]
        
        if not theme:
            theme = "mysterious adventure"
        
        return theme
    
    def _create_story(self, theme: str) -> str:
        """Create a complete story"""
        # Generate story parts
        opening = self._generate_opening(theme)
        conflict = self._generate_conflict(theme)
        development = self._generate_development(theme)
        climax = self._generate_climax(theme)
        resolution = self._generate_resolution(theme)
        
        story = f"{opening}\n\n{conflict}\n\n{development}\n\n{climax}\n\n{resolution}"
        
        # Add more paragraphs to reach desired length
        while len(story.split('\n')) < 30:
            story += f"\n\n{self._generate_paragraph(theme)}"
        
        return story
    
    def _generate_opening(self, theme: str) -> str:
        """Generate story opening"""
        openings = [
            f"In the heart of a world consumed by {theme}, a hero would rise.",
            f"Long before recorded history, the seeds of {theme} were planted.",
            f"It began on an ordinary day, when everything changed forever.",
            f"The legend of {theme} starts with a simple choice.",
            f"In a land where {theme} was both gift and curse, a destiny awaited."
        ]
        
        return random.choice(openings)
    
    def _generate_conflict(self, theme: str) -> str:
        """Generate story conflict"""
        conflicts = [
            f"As the forces of {theme} gathered, our protagonist faced impossible odds.",
            f"Little did they know that the greatest challenge of {theme} was yet to come.",
            f"Conflict erupted, testing everything they believed about {theme}.",
            f"The first signs of trouble appeared, hinting at the darkness to come.",
            f"An ancient enemy, drawn by the power of {theme}, began to stir."
        ]
        
        return random.choice(conflicts)
    
    def _generate_development(self, theme: str) -> str:
        """Generate story development"""
        return f"The journey through {theme} revealed hidden truths and forged unexpected alliances. Each step brought new challenges, but also new hope. The path was unclear, but determination never wavered."
    
    def _generate_climax(self, theme: str) -> str:
        """Generate story climax"""
        return f"In the final confrontation, the true meaning of {theme} became clear. Everything led to this moment, where choices would echo through eternity."
    
    def _generate_resolution(self, theme: str) -> str:
        """Generate story resolution"""
        return f"Peace returned, but {theme} would never be forgotten. The lessons learned would shape generations to come, a testament to courage and hope."
    
    def _generate_paragraph(self, theme: str) -> str:
        """Generate additional paragraphs"""
        paragraphs = [
            f"The echoes of {theme} resonated through the land, touching all who heard the tale.",
            f"Years passed, but the memory of those events remained vivid in the minds of all.",
            f"New challenges would arise, but the wisdom gained would guide them forward.",
            f"The legacy of {theme} became legend, inspiring others to seek their own path."
        ]
        
        return random.choice(paragraphs)
    
    def _generate_continuation(self, theme: str, lines: int) -> str:
        """Generate continuation to reach line count"""
        continuation = "\n\n"
        for i in range(lines // 3 + 1):
            continuation += f"{self._generate_paragraph(theme)}\n\n"
        return continuation
    
    def generate_article(self, prompt: str) -> str:
        """Generate a well-structured article"""
        topic = self._extract_theme(prompt)
        
        article = f"""📝 **Article: {topic.title()}**

## Introduction
{topic} represents one of the most fascinating subjects of our time. From its origins to its modern applications, understanding {topic} opens doors to new perspectives and possibilities.

## Historical Context
The story of {topic} spans generations, evolving with human knowledge and technology. Early thinkers laid the groundwork for today's understanding, each contribution building upon the last.

## Key Concepts
Several fundamental concepts form the foundation of {topic}:
• Core principles that define its nature
• Practical applications in daily life
• Theoretical frameworks for deeper understanding
• Emerging trends shaping its future

## Current Applications
Today, {topic} finds expression in countless ways:
- Technology and innovation
- Scientific research
- Cultural impact
- Economic implications

## Future Perspectives
Looking ahead, the future of {topic} holds exciting possibilities. Researchers continue to push boundaries, discovering new applications and deeper insights.

## Conclusion
{topic} remains a vibrant field of study and practice. As we continue to explore its depths, new questions arise alongside answers, ensuring the journey of discovery never truly ends.

---
*This article was generated by Skatlaz AI*
"""
        return article
    
    def generate_code(self, prompt: str, language: str = "python") -> str:
        """Generate code based on prompt"""
        # Detect language from prompt
        if "javascript" in prompt.lower() or "js" in prompt.lower():
            language = "javascript"
        elif "html" in prompt.lower():
            language = "html"
        elif "css" in prompt.lower():
            language = "css"
        
        # Extract functionality
        functionality = self._extract_functionality(prompt)
        
        if language == "python":
            code = self._generate_python_code(functionality)
        elif language == "javascript":
            code = self._generate_javascript_code(functionality)
        elif language == "html":
            code = self._generate_html_code(functionality)
        else:
            code = self._generate_python_code(functionality)
        
        # Fix: Properly close the f-string by using string concatenation
        result = "💻 **Generated " + language.upper() + " Code**\n\n"
        result += "**Functionality:** " + functionality + "\n\n"
        result += "```" + language + "\n"
        result += code + "\n"
        result += "```\n\n"
        result += "📝 **Explanation:**\n"
        result += "This code implements " + functionality + " using best practices and includes error handling for robust execution.\n"
        
        return result
    
    def _extract_functionality(self, prompt: str) -> str:
        """Extract desired functionality from prompt"""
        # Remove code-related words
        functionality = re.sub(r'(code|generate|create|write|make|program|script|function|class)', 
                              '', prompt, flags=re.IGNORECASE)
        functionality = functionality.strip()
        
        if not functionality:
            functionality = "a simple program"
        
        return functionality
    
    def _generate_python_code(self, functionality: str) -> str:
        """Generate Python code"""
        code = f'''"""
{functionality} - Generated by Skatlaz AI
"""

import sys
import logging

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def main():
    """Main function implementing {functionality}"""
    try:
        print("Starting {functionality}...")
        
        # Implementation
        result = perform_operation()
        
        print(f"Result: {{result}}")
        logger.info("Operation completed successfully")
        
    except Exception as e:
        logger.error(f"Error: {{e}}")
        sys.exit(1)

def perform_operation():
    """Core operation for {functionality}"""
    # Add your implementation here
    return "Operation completed"

if __name__ == "__main__":
    main()
'''
        return code
    
    def _generate_javascript_code(self, functionality: str) -> str:
        """Generate JavaScript code"""
        code = f'''/**
 * {functionality} - Generated by Skatlaz AI
 */

class Application {{
    constructor() {{
        this.initialize();
    }}
    
    initialize() {{
        console.log("Initializing {functionality}...");
        this.setupEventListeners();
    }}
    
    setupEventListeners() {{
        // Add event listeners
        document.addEventListener('DOMContentLoaded', () => {{
            this.run();
        }});
    }}
    
    run() {{
        try {{
            const result = this.performOperation();
            console.log(`Result: ${{result}}`);
            this.displayResult(result);
        }} catch (error) {{
            console.error("Error:", error);
        }}
    }}
    
    performOperation() {{
        // Core implementation
        return "Operation completed successfully";
    }}
    
    displayResult(result) {{
        const output = document.getElementById('output');
        if (output) {{
            output.textContent = result;
        }}
    }}
}}

// Start application
new Application();
'''
        return code
    
    def _generate_html_code(self, functionality: str) -> str:
        """Generate HTML/CSS/JS code"""
        current_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        
        code = f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{functionality.title()}</title>
    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 20px;
        }}
        
        .container {{
            background: white;
            border-radius: 10px;
            padding: 40px;
            max-width: 800px;
            width: 100%;
            box-shadow: 0 10px 30px rgba(0,0,0,0.2);
        }}
        
        h1 {{
            color: #667eea;
            margin-bottom: 20px;
        }}
        
        .content {{
            margin: 20px 0;
            line-height: 1.6;
        }}
        
        button {{
            background: #667eea;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            margin-top: 20px;
            transition: transform 0.3s;
        }}
        
        button:hover {{
            background: #764ba2;
            transform: translateY(-2px);
        }}
        
        footer {{
            margin-top: 30px;
            text-align: center;
            color: #666;
            font-size: 12px;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>{functionality.title()}</h1>
        <div class="content">
            <p>This page was generated by Skatlaz AI for: {functionality}</p>
            <button onclick="alert('Hello from Skatlaz AI!')">Click Me</button>
        </div>
        <footer>
            <small>Generated by Skatlaz AI - {current_time}</small>
        </footer>
    </div>
</body>
</html>'''
        return code
