#pip install requests beautifulsoup4 googlesearch-python sentence-transformers faiss-cpu numpy

import requests
import json
import numpy as np
import faiss
from bs4 import BeautifulSoup
from googlesearch import search
from sentence_transformers import SentenceTransformer

# =========================================================
# 🤖 SKATLAZ AI CORE MEMORY (RAG)
# =========================================================
embedder = SentenceTransformer("all-MiniLM-L6-v2")

dim = 384
index = faiss.IndexFlatL2(dim)
memory_store = []


def remember(text):
    vec = embedder.encode([text])[0]
    index.add(np.array([vec]).astype("float32"))
    memory_store.append(text)


def recall(query, k=5):
    if not memory_store:
        return []
    vec = embedder.encode([query])[0]
    D, I = index.search(np.array([vec]).astype("float32"), k)
    return [memory_store[i] for i in I[0] if i < len(memory_store)]


# =========================================================
# 🌐 WEB ENGINE
# =========================================================
def google_search(query):
    try:
        return [u for u in search(query, num_results=5)]
    except:
        return []


def crawl(url):
    try:
        r = requests.get(url, timeout=10, headers={"User-Agent": "Mozilla/5.0"})
        soup = BeautifulSoup(r.text, "html.parser")
        return soup.get_text(" ", strip=True)[:2500]
    except:
        return ""


def web_research(query):
    links = google_search(query)
    return "\n".join([crawl(l) for l in links[:3]])


# =========================================================
# 🌤️ WEATHER MODULE (FREE API)
# =========================================================
def get_weather(city="Sao Paulo"):
    try:
        geo = requests.get(
            f"https://geocoding-api.open-meteo.com/v1/search?name={city}"
        ).json()

        lat = geo["results"][0]["latitude"]
        lon = geo["results"][0]["longitude"]

        weather = requests.get(
            f"https://api.open-meteo.com/v1/forecast?latitude={lat}&longitude={lon}&current_weather=true"
        ).json()

        return weather["current_weather"]
    except:
        return {"error": "weather unavailable"}


# =========================================================
# 🧠 SWARM AGENTS
# =========================================================
def planner(goal):
    return f"Planejamento: pesquisar, analisar, validar e sintetizar sobre: {goal}"


def researcher(goal):
    return web_research(goal)


def analyst(data):
    return data[:2000]


def critic(data):
    return "Checagem: possíveis lacunas e inconsistências em fontes web."


def writer(goal, analysis, memory):
    return f"""
📘 SKATLAZ REPORT

🎯 Query:
{goal}

🧠 Memory:
{memory}

🔎 Analysis:
{analysis}

⚖️ Critic:

- Automatic verification applied
- Data may contain web noise

✅ Conclusion:
Synthesis generated by a swarm of Skatlaz AI agents.
"""


# =========================================================
# 🧠 CORE ORCHESTRATOR
# =========================================================
def run_swarm(goal, cycles=2):
    mem = recall(goal)

    final = None

    for _ in range(cycles):
        data = researcher(goal)
        analysis = analyst(data)
        critique = critic(data)

        final = writer(goal, analysis, mem)

        remember(str({
            "goal": goal,
            "data": data,
            "analysis": analysis,
            "critique": critique
        }))

    return final


# =========================================================
# 💬 CHAT ENGINE (MULTI MODE)
# =========================================================
def chat(user_input):

    text = user_input.lower()

    # 🌤️ WEATHER MODE
    if "tempo" in text or "clima" in text:
        return get_weather("Sao Paulo")

    # 🔎 RESEARCH MODE
    elif "pesquisa" in text or "pesquisar" in text:
        return run_swarm(user_input)

    # 📖 STORY MODE
    elif "história" in text or "story" in text:
        return f"📖 História gerada:\n{user_input} se transforma em narrativa dinâmica e estruturada."

    # 💻 CODE MODE
    elif "código" in text or "code" in text:
        return f"💻 Código gerado:\n# Skatlaz AI code output placeholder for: {user_input}"

    # 💬 GENERAL MODE
    else:
        return f"🤖 Skatlaz resposta:\n{user_input}"


# =========================================================
# 🚀 STARTUP (PEDIDO DO USUÁRIO)
# =========================================================
if __name__ == "__main__":

    print("🤖 Skatlaz AI starting...\n")

    while True:
        user_input = input("🤖 Ask to Skatlaz:\n")

        if user_input.lower() in ["exit", "quit", "sair"]:
            break

        result = chat(user_input)

        print("\n═══════════════════════════\n")
        print(result)
        print("\n═══════════════════════════\n")
